image: "nixos/unstable"
sources:
  - https://github.com/diamondburned/tasmospa
packages:
  - nixos.gnutar
artifacts:
  - build.tar.gz
tasks:
  - build: |-
      cd tasmospa
      nix-shell shell.nix --run '
        npm run build
        npm i
      '
  - artifact: |-
      tar -zcvf ../build.tar.gz ./build/
